# Generated by Django 2.0.4 on 2018-05-18 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('reg_date', models.DateTimeField(verbose_name='reg date')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedbackcust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeddetail', models.CharField(max_length=200)),
                ('feedto', models.CharField(max_length=200)),
                ('feed_date', models.DateTimeField(verbose_name='feed date')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrmapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Feedbackown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeddetail', models.CharField(max_length=200)),
                ('feedto', models.CharField(max_length=200)),
                ('feed_date', models.DateTimeField(verbose_name='feed date')),
            ],
        ),
        migrations.CreateModel(
            name='Ownerreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('reg_date', models.DateTimeField(verbose_name='reg date')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roombook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=100)),
                ('customerid', models.CharField(max_length=100)),
                ('bookdate', models.DateTimeField(verbose_name='booking date')),
            ],
        ),
        migrations.CreateModel(
            name='Roomdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownemail', models.CharField(max_length=100)),
                ('roomtitle', models.CharField(max_length=100)),
                ('roomdetails', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('roomimg', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('adddate', models.DateTimeField(verbose_name='adddate')),
                ('price', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=200)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrmapp.Category')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackown',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrmapp.Ownerreg'),
        ),
    ]
