# Generated by Django 2.0.4 on 2018-05-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrmapp', '0002_auto_20180519_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
