# Generated by Django 2.0.4 on 2018-05-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrmapp', '0003_massege'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='massege',
            name='reply',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
