# Generated by Django 2.0.4 on 2018-05-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrmapp', '0005_city_country_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='s',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myrmapp.State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='c',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myrmapp.Country'),
            preserve_default=False,
        ),
    ]
