# Generated by Django 2.0.4 on 2018-06-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrmapp', '0006_auto_20180525_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombook',
            name='mobile',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='massege',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
