# Generated by Django 2.0.4 on 2018-06-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrmapp', '0007_auto_20180604_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombook',
            name='bookdate',
            field=models.CharField(max_length=100),
        ),
    ]
